// scripts/gen-assets.mjs — regenerate the text assets bundled into the web extension:
//   src/providers/bob/prompts.ts  from docs/kit/03-runtime-prompts/*.md + contracts/schemas/stage-*.schema.json
//   src/exec/ci/templates.ts      from templates/ci/{reprise-run.yml,run-loop.mjs}
// Run: npm run gen:assets. test/bob-provider.test.ts fails if a generated file drifts.

import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, '..', '..', '..');
const STAGES = ['intake', 'dedupe', 'test', 'rootcause', 'fix', 'review'];

const read = (...p) => readFileSync(join(...p), 'utf8').replace(/\r\n/g, '\n');

export function parsePromptFile(text) {
  const m = text.replace(/\r\n/g, '\n').match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (!m) throw new Error('missing front matter');
  const vars = m[1].match(/variables:\s*\[([^\]]*)\]/);
  if (!vars) throw new Error('missing variables list');
  return {
    variables: vars[1].split(',').map((v) => v.trim()).filter(Boolean),
    body: m[2].trim(),
  };
}

// ── Bob prompts ──────────────────────────────────────────────────────────────

const kit = join(repoRoot, 'docs', 'kit', '03-runtime-prompts');
const schemas = join(here, '..', 'src', 'contracts', 'schemas');
const promptsOut = join(here, '..', 'src', 'providers', 'bob', 'prompts.ts');

const promptEntries = STAGES.map((stage) => {
  const { variables, body } = parsePromptFile(read(kit, `${stage}.md`));
  return `  ${stage}: {\n    variables: ${JSON.stringify(variables)},\n    body: ${JSON.stringify(body)},\n  },`;
});

const schemaEntries = STAGES.map((stage) => {
  // eslint-disable-next-line no-unused-vars
  const { $schema, $id, title, ...schema } = JSON.parse(read(schemas, `stage-${stage}.schema.json`));
  return `  ${stage}: ${JSON.stringify(JSON.stringify(schema))},`;
});

writeFileSync(
  promptsOut,
  [
    '// providers/bob/prompts.ts — GENERATED by scripts/gen-assets.mjs from',
    '// docs/kit/03-runtime-prompts/*.md and contracts/schemas/stage-*.schema.json.',
    '// Do not edit by hand; run `npm run gen:assets`.',
    '',
    "import type { Stage } from '../../contracts/enums';",
    '',
    'export interface PromptTemplate {',
    '  /** Every variable the template uses; a missing one is an error (03-runtime-prompts/README.md). */',
    '  variables: string[];',
    '  body: string;',
    '}',
    '',
    'export const PROMPTS: Record<Stage, PromptTemplate> = {',
    ...promptEntries,
    '};',
    '',
    '/** Stage output JSON Schemas (contracts/schemas/stage-*.schema.json), appended to every prompt. */',
    'export const SCHEMAS: Record<Stage, string> = {',
    ...schemaEntries,
    '};',
    '',
  ].join('\n'),
);
console.log(`Wrote ${promptsOut}`);

// ── CI templates ─────────────────────────────────────────────────────────────

const ciDir = join(repoRoot, 'templates', 'ci');
const ciOut = join(here, '..', 'src', 'exec', 'ci', 'templates.ts');

writeFileSync(
  ciOut,
  [
    '// exec/ci/templates.ts — GENERATED by scripts/gen-assets.mjs from templates/ci/.',
    '// Do not edit by hand; run `npm run gen:assets`.',
    '',
    '/** Files "Reprise: Set Up CI Runs" commits to the target repository (PD-14). */',
    'export const CI_TEMPLATES: ReadonlyArray<{ path: string; content: string }> = [',
    `  { path: '.github/workflows/reprise-run.yml', content: ${JSON.stringify(read(ciDir, 'reprise-run.yml'))} },`,
    `  { path: '.reprise/ci/run-loop.mjs', content: ${JSON.stringify(read(ciDir, 'run-loop.mjs'))} },`,
    '];',
    '',
  ].join('\n'),
);
console.log(`Wrote ${ciOut}`);
